[package]
name = "tg-message-tally"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.2.2"
serde = "1.0.39"
serde_derive = "1.0.188"
serde_json = "1.0.105"
winapi = { version = "0.3", features = ["winuser"]}

[profile.release]
panic = "abort"